# lsi: false
# safe: true
# incremental: false
# highlighter: rouge
# gist:
  # noscript: false
# kramdown:
  # math_engine: mathjax
  # syntax_highlighter: rouge

title: kwongh.github.io
email: kkh518@hotmail.com
github_username:  kwongh

# Build settings
theme: minima
permalink: pretty
# plugins:
  # - jekyll-default-layout  
